[package]
name = "error_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
thiserror = "1.0.60"
error-info-derive = { workspace = true }
http = "1.1.0"
